#!/bin/sh
# Generated by SpecBuddy (spec-buddy-comment-submit-hook) — do not edit by hand.
PAYLOAD=$(cat)

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$PWD}"
for port in $(seq 63500 63519); do
  reply=$(curl -sf -G --connect-timeout 1 --data-urlencode "path=$PROJECT_DIR" \
    -w '\n%{url_effective}' "http://127.0.0.1:$port/comment-submit/owns" 2>/dev/null)
  owns=$(printf %s "$reply" | sed '$d')
  query=$(printf %s "$reply" | tail -n 1 | sed 's/^[^?]*//')
  if echo "$owns" | grep -q '"owns":true'; then
    curl -s --max-time 300 -X POST "http://127.0.0.1:$port/comment-submit$query" --data-binary "$PAYLOAD"
    break
  fi
done